### ISSUE TITLE
Style: change "Get Started" text color to white in dark mode

### ISSUE THREAD

**Issue by Maianki** [Maianki/Shuttle-UI#17]
## The get started text should be in white color in dark-mode
![dark-mode](https://user-images.githubusercontent.com/28630412/190846522-63a1d547-324d-405b-b704-a377ac508045.JPG)

**Comment by abitsalihu** [comment]
@Maianki I would like to help on this issue. :)

**Comment by Maianki** [comment]
> @Maianki I would like to help on this issue. :)

Sorry @abitsalihu . @Manoharvuradi has already raised the PR for this and it was a very beginner friendly issue. Hope you don't mind.
