### ISSUE TITLE
dx: add a CONTRIBUTE.md file

### ISSUE THREAD

**Issue by Maianki** [Maianki/Shuttle-UI#18]
## We don't have any documentation right now on how someone can start contributing to the project.

- [ ] Create a CONTRIBUTE.md file which describes all the steps to get started with contributing to the project.

### Sources to refer 
[CONTRIBUTE.md template](https://gist.github.com/PurpleBooth/b24679402957c63ec426)

**Comment by abitsalihu** [comment]
@Maianki I would like to help on this issue by creating a contribution guide for newcomers. :)

**Comment by Maianki** [comment]
@abitsalihu Thanks for showing interest. Assigning it to you. Do let me know if you need any help and please specify an ETA for this.
