### ISSUE TITLE
Create sidebar for smaller screen

### ISSUE THREAD

**Issue by Maianki** [Maianki/Shuttle-UI#21]
Right now the documentation website do not have a sidebar for smaller screen. Add sidebar menu which open and closes on smaller Viewport sizes.
# Desktop view of documentation page.
![Screenshot (870)](https://user-images.githubusercontent.com/28630412/193402936-43c2c046-6f1e-4817-9442-71eec84bc3d4.png)

 # Mobile View of documentation page. 
![Screenshot (871)](https://user-images.githubusercontent.com/28630412/193402942-1d822431-2c3e-4d8f-90b2-a560ab4acc7a.png)

On right to the logo of website add a Hamburger icon which closes and open the sidebar in smaller Viewport screen. For the screens where sidebar is visible the hamburger should not be visible.

**Comment by htcni** [comment]
Hi,
I would like to work on this issue.

**Comment by Maianki** [comment]
> Hi, I would like to work on this issue.

Sure @htcni assigning this to you. Please do reach to me in-case you need any help. You can checkout CONTRIBUTING.md file to know how to get start with contributing to the repository.

**Comment by htcni** [comment]
Hey @Maianki do you want the hamburger menu after the dark mode icon?

**Comment by Maianki** [comment]
@htcni can you please put it on the right? because our sidebar for larger viewport is also on right side.
