### ISSUE TITLE
Fix the documentation and github link alignment in the navbar 

### ISSUE THREAD

**Issue by Maianki** [Maianki/Shuttle-UI#25]
For viewport width greater than 500px (aprox.) the links to github and documentation is well aligned. But less than 500px(aprox.) width of the icons and their respective text are getting wrapped. For viewport size less than 500px(aprox.) we can have only the icons of the links so the alignment does not get affected.

## For viewport size greater than 500px
![Screenshot (876)](https://user-images.githubusercontent.com/28630412/193985331-397a36e3-0e9b-4413-87ba-d8283f9f7c9a.png)

## For viewport size less than 500px
![Screenshot (877)](https://user-images.githubusercontent.com/28630412/193985337-765a879a-08a1-4a65-859a-25c87f819711.png)

**Comment by sarthakbartwal** [comment]
Hey! . I will resolve this issue

**Comment by Maianki** [comment]
> Hey! . I will resolve this issue

@babbu47 Thanks, for showing interest, assigning this to you. Do go through the CONTRIBUTE.md and let me know if you need any help.
