### ISSUE TITLE
add a tooltip on dark/light mode toggle button and change the icon on toggle

### ISSUE THREAD

**Issue by Maianki** [Maianki/Shuttle-UI#28]
Add a tooltip on dark/light mode button and change the icon[moon when light mode is on and sun when dark mode is on] based on the mode.

![nav](https://user-images.githubusercontent.com/28630412/194612925-aa30a13a-5880-47ca-b99a-e0bb5664c9cb.JPG)

**Comment by RohitSaklani** [comment]
hey there , I would like to contribute to this issue .

**Comment by Maianki** [comment]
@RohitSaklani thanks, assigning it to you.
